config/routes.rb
Rails.application.routes.draw do
  root "leagues#index"
  devise_for :users
  resources :leagues
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/league.rb
class League < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
has_many :leagues
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!
  protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
    end
end

app/controllers/leagues_controller.rb
class LeaguesController < ApplicationController
  before_action :set_league, only: [:show, :edit, :update, :destroy]

  def index
    @leagues = current_user.leagues
  end

  def show
  end

  def create
    @league = current_user.leagues.new(league_params)
    if @league.save
      flash[:success] = "League Created"
      redirect_to leagues_path
    else
      flash[:error] = "Error #{@league.errors.full_messages.join("\n")}"
      render :new
    end
  end

  def new
    @league = League.new
  end

  def edit
  end
  
  def update
    if @league.update(league_params)
      redirect_to leagues_path
    else
      render :edit
    end
  end

  def destroy
    @league.destroy 
    redirect to leagues_path
  end
private
    def league_params
      params.require(:league).permit(:name, :character)
    end

    def set_league
      @league = current_user.leagues.find(params[:id])
    end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/leagues_helper.rb
module LeaguesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RiotAccount</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="container">
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>"><%= value %></div>
    <% end %>
    <%= yield %>
  </div>
  </body>
</html>

app/views/leagues/edit.html.erb
<h1>Leagues#edit</h1>
<p>Find me in app/views/leagues/edit.html.erb</p>

app/views/leagues/index.html.erb
<%= button_to "Log Out", destroy_user_session_path, method: :delete %>
<h2>Welcome <%= current_user.first_name %></h2>
<hr />
<%= link_to "Add League", new_league_path %>
<h3>Your League</h3>
<ul>
  <% @leagues.each do |league| %>
    <li>
      <%= league.name %> - <%= league.character %>
    </li>
  <% end %>
</ul>

app/views/leagues/new.html.erb
<h1>Add League</h1>
<%= form_with(model: @league, local: true) do |f| %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, required: true, placeholder: "Name" %>
  </div>

  <div class="field">
    <%= f.label :character %>
    <%= f.text_field :name, required: true, placeholder: "Name" %>
  </div>
  <%= f.submit %>
<% end %>

app/views/leagues/show.html.erb
<h1>Leagues#show</h1>
<p>Find me in app/views/leagues/show.html.erb</p>